//LCD PIN CONNECTIONS DEFINES
//DATA PINS
#define DPINS 18

//REGISTER SELECT AND ENABLE PINS
#define RS 4
#define EN 5

//LCD DEFINES
#define CLEAR_LCD           0X01
#define DISP_ON_CUR_BLINK   0X0F
#define DISP_ON_CUR_OFF     0X0C
#define SHIFT_CUR_RIGHT     0X06
#define MODE_8BIT_1LINE     0X30
#define MODE_8BIT_2LINE     0X38
#define GOTO_LINE1_POS0     0X80
#define GOTO_LINE2_POS0     0XC0

