//MACRO DEFINES
#define WRITEBYTE(WORD,BITPOS,VAL)  WORD=(WORD&~(255<<BITPOS)|(VAL<<BITPOS))
#define WRITENIBBLE(WORD,BITPOS,VAL)  WORD=(WORD&~(15<<BITPOS)|(VAL<<BITPOS))
#define WRITEBIT(WORD,BITPOS,VAL)  WORD=(WORD&~(1<<BITPOS)|(VAL<<BITPOS))
#define READNIBBLE(WORD,BITPOS)    ((WORD>>BITPOS)&15)
#define READBIT(WORD,BITPOS)    ((WORD>>BITPOS)&1)
